name: Test Push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run ESLinter
        run: npm run lint
      - name: Run Tests
        run: npm run test
